name: inventor
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: Inventor News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dddedd'
    - '#a8acac'
    - '#231f20'
    - '#545254'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
